# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["ahci" "xhci_pci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/8be3b4e5-7219-4427-bba4-340f1dc4b868";
      fsType = "ext4";
    };

    "/mnt/disk1" = {
      device = "/dev/disk/by-uuid/3c4b5d00-43c0-48be-81b8-c2b3977e015b";
      fsType = "ext4";
      options = ["nofail" "x-systemd.automount"];
    };

    "/mnt/disk2" = {
      device = "/dev/disk/by-uuid/98a75e01-fa80-469e-820c-1e1e275937b8";
      fsType = "ext4";
      options = ["nofail" "x-systemd.automount"];
    };

    "/mnt/disk3" = {
      device = "/dev/disk/by-uuid/0301db98-264f-4b18-9423-15691063f73d";
      fsType = "ext4";
      options = ["nofail" "x-systemd.automount"];
    };

    "/mnt/parity" = {
      device = "/dev/disk/by-uuid/6cce037c-d2d4-4940-bb69-6d2b84fd41aa";
      fsType = "ext4";
      options = ["nofail" "x-systemd.automount"];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/7C10-C8BD";
      fsType = "vfat";
    };
  };

  swapDevices = [{device = "/dev/disk/by-uuid/edb5324f-3cd2-4b8c-bb05-cca045adeaf6";}];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
